http.encoding: #表示用于解码URI的字符编码。
  charset: UTF-8
  enable: true
  force: true

server:
  port: 8801

spring.datasource:
  driver-class-name: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: 123456

mybatis:
  mapper-locations: classpath*:mybatis/*Mapper.xml #mybatis xml配置文件对应地址 resources->mybatis
  type-aliases-package: com.example.*
  reloadMapper.enabled: true
  dbColumnUnderline: true

spring:
  rabbitmq:
    addresses: 192.168.1.188
    port: 5672
    username: joker
    password: joker
    virtual-host: /
  profiles:
    active: direct #测试交换器类型：direct、fanout、topic

rabbitmq:
  config:
    queue:
      name: spring-boot-queue
      descript: 队列
    exchange:
      name: spring-boot-exchange
      descript: 交换机
    routing:
      key: spring-boot-key